use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'


target 'LJJNetWork_Example' do
  pod 'LJJNetWork', :path => '../'

  target 'LJJNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
